### ISSUE TITLE
Are projects using this action following SPEC 4?

### ISSUE THREAD

**Issue by mattip** [scientific-python/upload-nightly-action#14]
In the SPEC it states
> **Process for Adding New Projects**

> After someone creates an issue on https://github.com/scientific-python/upload-nightly-action requesting access to upload wheels a human/admin has to respond to that request.

Maybe I am missing something, but I do not see issues here for the projects using the site.

**Comment by matthewfeickert** [comment]
@mattip I think @Carreau, @bsipocz, and @betatim can give you more context of the wording there given the 2023 summit and PR https://github.com/scientific-python/specs/pull/195, but I think(?) the reason that you're not seeing people make issues to request access is that all the projects that are using the action already had access to https://anaconda.org/scientific-python-nightly-wheels from the start. So maybe these instructions are useful for maintainers of new projects that want to start publishing nightly wheels on the scientific-python-nightly-wheels package index.

**Comment by mattip** [comment]
OK, thanks. I was troubled by this sentenct in [SPEC 4](https://scientific-python.org/specs/spec-0004/): 
> Admins are people from the community who are ideally not part of the same organizations nor project. This is to prevent malicious activities from a given group of actors and ensure a diverse and healthy community. Adding new people to the list of admins requires at least an issue to be openned.

and wanted to see how the two parts were working out in practice:
- the requirement to open an issue
- admins are people not from the same project: is the intent that an admin for NumPy be someone from, say, Pandas?

**Comment by matthewfeickert** [comment]
@mattip This would probably be worth an Issue on https://github.com/scientific-python/specs/issues to discuss. (I have a few SPEC4 things on my TODO list as well, so I'll probably join you in doing so next week).

**Comment by betatim** [comment]
The reason there are no issues is probably because people were in a room together. It would have been nice to have an issue even though people could talk in person, to create a "paper trail" (mostly so people from the future can work out what happened in the past). However, getting hybrid (in person + async) to work is even harder than just getting async to work :(

Regarding the "different projects": I think this is something worth rephrasing. There are two kinds of "admins": those of the anaconda space and those who are added to the anaconda project for a particular open-source project. Disambiguating them would be good. For the "admins of the anaconda project" the intention is to have people from across the community, so here "project" is meant to read as "open-source project". Also you don't want all of them to be in the same timezone or work for the same company. Then for the per project admins (e.g. from numpy) the idea is not to have pandas people in the mix, it should be just people from numpy. Probably the same logic about different timezones and employers, etc applies though.

If someone has an idea on how to rephrase it, PRs to the SPEC's text would be welcome.

**Comment by bsipocz** [comment]
There are some tracking issues where we tried to check the core packages whether they upload their wheels into this new location, and whether they test with their upstream dev versions.

Otherwise, indeed we have relied a little too much on the in person element, and didn't do per project, individual uses. I'm so sorry about that.

**Comment by tupui** [comment]
Yes there might be some rewording needed. The first part is about admins of the anaconda org specifically (about opening an issue, etc.)

And the second part is about admin of your group containing your package. The rules should ideally be the same in both cases. Just that the check/due diligence is not done at the same level. On our side, we would check that your project is legitimate and "worth" including in the list, and you would be responsible of providing trustees for your project.

**Comment by mattip** [comment]
> This would probably be worth an Issue on https://github.com/scientific-python/specs/issues

See https://github.com/scientific-python/specs/issues/223. Would people prefer to continue the discussion there?

**Comment by jarrodmillman** [comment]
This discussion continues on https://github.com/scientific-python/specs/issues/223.
