### ISSUE TITLE
switching `xarray` away from a global token

### ISSUE THREAD

**Issue by keewis** [scientific-python/upload-nightly-action#58]
As requested in #57 (and as a separate issue in order not to hijack that one), I've been looking at switching the `xarray` token to something that is not global. However, I couldn't find any documentation on how to do that (nor figure it out myself). Note that the global `xarray` token that was still active was replaced by a personal token about 4 months ago, and it is now revoked.

Somewhat relatedly, I've also not been a member of the `xarray` group, but this I could easily fix since I had been a member of the global organization (I'd be fine with relinquishing that additional power, which I don't really need).

Can anyone explain to me what needs to be done to migrate the token?

**Comment by matthewfeickert** [comment]
Thanks @keewis! I think that @tupui can probably give you a good short summary here of how to move forward.

**Comment by tupui** [comment]
Hi @keewis, thanks for the fast reply 😃 

I will remove you from the admins then as to keep the list more "manageable" and have more separation of responsibilities between all of us. Which is the goal of having teams.

To create your personal token you need to be connected with your account

1. on the top right corner check that you are on your profile, you can click on `Switch to...` if that's not the case
2. Under settings/Access you can create a token
3. Create the token with proper scope and expiry (ideally not rotate every year or so.)

<img width="1200" alt="Screenshot 2024-01-25 at 00 18 25" src="https://github.com/scientific-python/upload-nightly-action/assets/23188539/25154263-1c47-4f77-969d-dc39b7c7e3df">

The doc is here https://scientific-python.org/specs/spec-0004/#process-for-adding-new-projects
Let me know if something is not clear and once you have done the change so that I can remove the old token. Thanks in advance 🚀

**Comment by tupui** [comment]
Actually seems like someone (hopefully you) already removed your global token. So I will close this issue.

**Comment by keewis** [comment]
yep, that was me (see the access log). Turns out we had done the migration already, and that token was unused.

> The doc is here https://scientific-python.org/specs/spec-0004/#process-for-adding-new-projects

Might I suggest to update the readme of this repository to either point there or say the same thing? That would have made that information easier to find.

> I will remove you from the admins then as to keep the list more "manageable" and have more separation of responsibilities between all of us.

When I joined the organization I also added @kmuehlbauer (and @jhamman? not sure) as a global admin. Before leaving the organization I added both to the `xarray` team, so I believe you should also be able to remove them from the global admins (once again, not sure, because there might be other reasons they're in that list – but you should have a better overview of that than I do).

**Comment by tupui** [comment]
Thank you 🙏 

I don't know for the other admins. I will bring that up in the next meeting.

**Comment by tupui** [comment]
And yes good suggestion for the readme
